import { Lang, OverlayConfig } from '../models/overlay.models';

export const PLACEHOLDER_COVER =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==';

export const STORAGE_KEY = 'bsCyberConfig';

export const DEFAULT_CONFIG: OverlayConfig = {
  lang: 'ru',
  theme: 'cyberpunk',
  ws: 'ws://127.0.0.1:2947/socket',
  customProxy: '',
  layout: 'top-left',
  scale: 1,
  blId: '',
  ssId: '',
  nameSource: 'beatleader',
  avatarSource: 'beatleader',
  resolvedBlId: '',
  resolvedBlQuery: '',
  resolvedSsId: '',
  resolvedSsQuery: '',
  showBL: true,
  showSS: false,
  showBLNextGlobal: false,
  showBLNextRegion: false,
  showBLNextFriends: false,
  showDebugUI: false,
  glowAvatar: true,
  showCover: true,
  showTitle: true,
  showArtist: true,
  showMeta: true,
  showBsr: true,
  showMapRatings: true,
  showSSStars: false,
  showProgress: true,
  showHp: true,
  showStats: true,
  showAcc: true,
  showMapBg: true,
  showBLBg: true
};

export const PROXIES = [
  '',
  'https://api.codetabs.com/v1/proxy?quest=',
  'https://api.allorigins.win/raw?url=',
  'https://corsproxy.io/?',
  'https://thingproxy.freeboard.io/fetch/'
];

export const I18N: Record<Lang, Record<string, string>> = {
  en: {
    sysSetup: 'SYSTEM SETUP [F2]',
    langLabel: 'Language / Язык',
    themeLabel: 'Theme',
    customProxyLabel: 'Custom Proxy Prefix',
    tabGeneral: 'General',
    tabBeatLeader: 'BL/SS',
    tabSongOverlay: 'Song Overlay',
    layoutLabel: 'Layout (Alignment)',
    scaleLabel: 'Scale (0.5 - 2.0)',
    blLabel: 'BeatLeader ID / Nickname',
    ssLabel: 'ScoreSaber ID / Nickname',
    nameSourceLabel: 'Nickname Source',
    avatarSourceLabel: 'Avatar Source',
    sourceBeatLeader: 'BeatLeader',
    sourceScoreSaber: 'ScoreSaber',
    blPlaceholder: 'Example: 76561198029377687',
    ssPlaceholder: 'Example: 76561198059961776',
    customProxyPlaceholder: 'Example: https://my-proxy.example/?url=',
    modulesLabel: 'Display Modules (On/Off)',
    modBl: 'BeatLeader Menu',
    modSs: 'ScoreSaber Menu',
    modBlNextGlobal: 'Next Global',
    modBlNextRegion: 'Next Region',
    modBlNextFriends: 'Next Following',
    modCover: 'Track Cover',
    modTitle: 'Track Title',
    modArtist: 'Artist / Mapper',
    modMeta: 'Difficulty & BPM',
    modBsr: 'BSR Code & Date',
    modMapRatings: 'BeatLeader Map Ratings',
    modSsStars: 'ScoreSaber Stars',
    modProg: 'Progress Bar',
    modHp: 'HP Bar (Health)',
    modStats: 'Miss / Combo',
    modAcc: 'Accuracy (Acc)',
    modGlow: 'Neon Glow',
    modDebug: 'Debug Messages',
    modMapBg: 'Map Card Background',
    modBlBg: 'BeatLeader Background',
    applyBtn: 'APPLY',
    waitingSong: 'Waiting for song...',
    loading: 'Loading...',
    profileNotFound: 'Profile not found',
    profileLoadError: 'Error loading profile'
  },
  ru: {
    sysSetup: 'СИСТЕМНЫЕ НАСТРОЙКИ [F2]',
    langLabel: 'Язык / Language',
    themeLabel: 'Тема',
    customProxyLabel: 'Свой Proxy Prefix',
    tabGeneral: 'Основные',
    tabBeatLeader: 'BL/SS',
    tabSongOverlay: 'Song Overlay',
    layoutLabel: 'Выравнивание (Layout)',
    scaleLabel: 'Масштаб (0.5 - 2.0)',
    blLabel: 'BeatLeader ID / Никнейм',
    ssLabel: 'ScoreSaber ID / Никнейм',
    nameSourceLabel: 'Источник никнейма',
    avatarSourceLabel: 'Источник аватара',
    sourceBeatLeader: 'BeatLeader',
    sourceScoreSaber: 'ScoreSaber',
    blPlaceholder: 'Например: 76561198029377687',
    ssPlaceholder: 'Например: 76561198059961776',
    customProxyPlaceholder: 'Например: https://my-proxy.example/?url=',
    modulesLabel: 'Модули отображения (Вкл/Выкл)',
    modBl: 'BeatLeader Меню',
    modSs: 'ScoreSaber Меню',
    modBlNextGlobal: 'Следующий Global',
    modBlNextRegion: 'Следующий Region',
    modBlNextFriends: 'Следующий Following',
    modCover: 'Обложка трека',
    modTitle: 'Название трека',
    modArtist: 'Исполнитель / Маппер',
    modMeta: 'Сложность и BPM',
    modBsr: 'BSR код и Дата',
    modMapRatings: 'Рейтинги BeatLeader',
    modSsStars: 'Звезды ScoreSaber',
    modProg: 'Прогресс-бар',
    modHp: 'HP Бар (Здоровье)',
    modStats: 'Промахи и Комбо',
    modAcc: 'Точность (Acc)',
    modGlow: 'Неоновое свечение',
    modDebug: 'Сообщения отладки',
    modMapBg: 'Фон карточки карты',
    modBlBg: 'Фон BeatLeader',
    applyBtn: 'ПРИМЕНИТЬ',
    waitingSong: 'Ожидание трека...',
    loading: 'Загрузка...',
    profileNotFound: 'Профиль не найден',
    profileLoadError: 'Ошибка загрузки профиля'
  }
};
